image:
  name: registry.digitalocean.com/polar-labs-registry/flutter-runner:3.24.4
  username: $DIGITALOCEAN_ACCESS_TOKEN
  password: $DIGITALOCEAN_ACCESS_TOKEN

definitions:
  steps:
    - step: &run-tests
        name: Run Tests
        script:
          - echo "tests tbd ..."

pipelines:
  pull-requests:
    "**": # this runs as default for any branch not elsewhere defined
      - step: *run-tests

  branches:
    main:
      - step: *run-tests
      - step:
          name: Mirror to GitHub
          image: alpine/git:latest  # Small alpine-based image with git and ssh pre-installed
          script:
            # bitbucket options will fetch just the current branch, so it is required to fetch all:
            - git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
            # fetch all branches:
            - git fetch --all
            # track all branches but HEAD and the current one, which is already being tracked:
            - for i in $(git branch -a | grep remotes | grep -v "HEAD" | grep -v "$(git rev-parse --abbrev-ref HEAD)"); do git branch --track ${i#remotes/origin/} $i; done
            # publish the current working copy to gtithub
            - git push --mirror $GITHUB_REPO_URL
