name: example_app
description: A new Flutter project.
version: 1.0.0+1

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`.
publish_to: 'none'

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  build_web_compilers:
  flutter_test:
    sdk: flutter

  build_runner:
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
