name: example_app
description: A new Flutter project.
version: 1.0.0+1

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`.
publish_to: 'none'

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  sentry_flutter: ^8.13.0
  cupertino_icons: ^1.0.2
  go_router: ^10.0.0
  google_fonts: ^5.1.0
  icons_plus: ^4.0.0
  collection: ^1.17.2
  json_annotation: ^4.9.0
  flutter_svg: ^2.0.16
  get_it: ^8.0.2
  dio: ^5.7.0
  flutter_hooks: ^0.20.5
  fquery: ^1.5.0-beta.1
  flutter_dotenv: ^5.2.1
  pretty_dio_logger: ^1.4.0
  url_launcher: ^6.3.1
  remixicon: ^1.3.0
  provider: ^6.1.2
  url_strategy: ^0.3.0
  package_info_plus: ^8.2.1
  web: ^1.1.0

dev_dependencies:
  build_web_compilers:
  flutter_test:
    sdk: flutter

  build_runner:
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - ./dotenv
  