namespace: ${APP_NAME}-${ENV_NAME}
appName: ${APP_NAME}
replicas: ${POD_REPLICAS}
imageLocation: ${IMAGE_NAME}
registrySecretName: ${REGISTRY_SECRET_NAME}
containerPorts:
  - name: http
    port: 8000
    targetPort: 8000
clusterIssuerName: ${CLUSTER_ISSUER}
tlsSecretName: tls-${APP_NAME}-${ENV_NAME}

# only set these env vars if we need to guarantee a certain amount of resources
# e.g. for a production environment, not a preview environment
resources:
  limits:
    cpu: "${POD_CPU_LIMIT}"
    memory: "${POD_MEMORY_LIMIT}"
  requests:
    cpu: "${POD_CPU_REQUEST}"
    memory: "${POD_MEMORY_REQUEST}"
    
hosts:
  - domainName: ${FULL_DOMAIN}
    ingressPaths:
      - path: /
        type: Prefix
        servicePort: 8000
